version: '3.8'
services:
  # ① Frontend のビルドステージのみ動かして dist をボリュームに出力
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules
#    command: npm run dev

  # ② Backend (FastAPI)
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}

volumes:
  frontend-dist: {}
